# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.
[backend]
type="semtech_udp"
[backend.semtech_udp]
udp_bind = "0.0.0.0:1700"
[backend.semtech_udp]
[integration.mqtt.auth.generic]
servers=["tcp://127.0.0.1:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="as923/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="as923/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="as923/gateway/{{ .GatewayID }}/command/#"
